library(shiny)
library(grid)
library(lattice)
library(latticeExtra)
library(tidyr)
library(dplyr)
library(shinyTree)
library(shinythemes)
library(dendextend)
library(reshape2)
library(ggplot2)
library( "limma" )
library(pheatmap)
library(ggrepel)
library(dplyr)
library(ggfortify)
library(ggstatsplot)
library(cluster)
library (gplots)
library(DT)
library(shinyvalidate)
options(connectionObserver = NULL)
library(GO.db)
library(org.Hs.eg.db)
library(topGO)
library(GSEABase)
library(clusterProfiler)
library(Rgraphviz)
library(pathview)
library(igraph)
library(ggnewscale)
library(WGCNA)
collectGarbage()

for (Rfile in list.files("R", "(heplbox).R", full.names = TRUE)) {
  source(Rfile, encoding = "utf-8")
}

# list of data files
datalistfiles <- list.files("data", pattern = "\\.Rdata$", full.names = TRUE)
# load all of them
for (path in datalistfiles) load(path)
datalistfiles <- gsub("^data/|.Rdata$", "", datalistfiles)

